//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lithnet.Miiserver.AutoSync.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lithnet.Miiserver.AutoSync.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This function is called by the MA executor before a run profile is executed. Return $false to prevent the run profile from being executed
        ///# Returning $true or nothing will allow the run profile to execute
        ///function ShouldExecute
        ///{
        ///	param([string]$runProfileName)
        ///
        ///	Write-Object $true;
        ///}
        ///
        ///# This function is called by the MA executor after a run profile is executed. The results of the run can be examined and acted upon if required.
        ///function ExecutionComplete
        ///{
        ///	param([Lithnet.Miiserver.Client.RunD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowerShellControllerScript {
            get {
                return ResourceManager.GetString("PowerShellControllerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Get-RunProfileToExecute 
        ///{
        ///    # Logic to determine what run profile to execute goes here
        ///    #
        ///    # Return the name of the run profile to execute using Write-Output as shown below
        ///    # 
        ///    # Write-Output &quot;FI&quot;; 
        ///    #
        ///    # If no run profile should be executed, then do not return anything
        ///    #
        ///}.
        /// </summary>
        internal static string PowerShellTriggerScript {
            get {
                return ResourceManager.GetString("PowerShellTriggerScript", resourceCulture);
            }
        }
    }
}
